[package]
name = "basler_video_capture"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.26"
show-image = "0.14.1"
pylon-cxx = "0.4.4"
clap = { version = "4.3.10", features = ["derive"] }

